version: "3.8"

services:
    react_typescript_app:
        container_name: reinforcement_react_typescript_app
        image: node:lts-alpine
        working_dir: /app
        ports:
            - 3001:3001
        volumes:
            - .:/app
        # entrypoint: ['npm', '']
        tty: true
        # env_file:
        # - ./.env
        # command: nodemon app.js
